name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: version
      run: echo "::set-output name=version::$(./bin/azblogfilter --version)"
      id: version
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: upload
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin/sigs-to-bits
        asset_name: sigs-to-bits
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ github.token }}